version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # uhttps://hub.docker.com/search?q=circleci&type=image
      - image: circleci/node:14.0.0-stretch
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            npm install
      # run lints!
      - run:
          name: run test
          command: |
            npm run test